name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Login to Docker Hub
     - uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build -f ./alsa/Dockerfile -t guidcruncher/pistereo2-mediaserver:alsa-latest --platform linux/arm64 --pull --push .
      run: docker buildx build -f ./pulseaudio/Dockerfile -t guidcruncher/pistereo2-mediaserver:pulseaudio-latest --platform linux/arm64 --pull --push .
      run: docker buildx build -f ./pipewire/Dockerfile -t guidcruncher/pistereo2-mediaserver:pipewire-latest --platform linux/arm64 --pull --push .
